{ ... }:

{
  imports = [
    ./alacritty/config.darwin.nix
    ./chrome/config.darwin.nix
    ./discord/config.darwin.nix
    ./docker/config.darwin.nix
    ./dropbox/config.darwin.nix
    ./figma/config.darwin.nix
    ./flux/config.darwin.nix
    ./fonts/config.darwin.nix
    ./geforce/config.darwin.nix
    ./homebrew/config.darwin.nix
    ./hue/config.darwin.nix
    ./jetbrains/config.darwin.nix
    ./kitty/config.darwin.nix
    ./kmonad/config.darwin.nix
    ./linear/config.darwin.nix
    ./logitech/config.darwin.nix
    ./macos/config.darwin.nix
    ./obsidian/config.darwin.nix
    ./one-password/config.darwin.nix
    ./postgresql/config.darwin.nix
    ./qmk/config.darwin.nix
    ./raspberry-pi/config.darwin.nix
    ./raycast/config.darwin.nix
    ./rclone/config.darwin.nix
    ./skhd/config.darwin.nix
    ./spotify/config.darwin.nix
    ./steam/config.darwin.nix
    ./supabase/config.darwin.nix
    ./tailscale/config.darwin.nix
    ./vscode/config.darwin.nix
    ./warp/config.darwin.nix
    ./yabai/config.darwin.nix
    ./zotero/config.darwin.nix
  ];
}
