{ ... }:

{
  imports = [
    ./bat/options.nix
    ./chrome/options.nix
    ./discord/options.nix
    ./dotnet/options.nix
    ./exa/options.nix
    ./fd/options.nix
    ./fish/options.nix
    ./fzf/options.nix
    ./geforce/options.nix
    ./git/options.nix
    ./home/options.nix
    ./homebrew/options.nix
    ./htop/options.nix
    ./hue/options.nix
    ./iosevka/options.nix
    ./jetbrains/options.nix
    ./jq/options.nix
    ./linear/options.nix
    ./logitech/options.nix
    ./macos/options.nix
    ./nix/options.nix
    ./node/options.nix
    ./obsidian/options.nix
    ./password/options.nix
    ./postgresql/options.nix
    ./prettyping/options.nix
    ./python/options.nix
    ./qmk/options.nix
    ./raspberry-pi/options.nix
    ./raycast/options.nix
    ./rclone/options.nix
    ./ripgrep/options.nix
    ./skhd/options.nix
    ./steam/options.nix
    ./tldr/options.nix
    ./vim/options.nix
    ./vscode/options.nix
    ./warp/options.nix
    ./yabai/options.nix
  ];
}
