{ ... }:

{
  imports = [
    ./alacritty/options.nix
    ./bat/options.nix
    ./caddy/options.nix
    ./chrome/options.nix
    ./discord/options.nix
    ./docker/options.nix
    ./dotnet/options.nix
    ./exa/options.nix
    ./factorio/options.nix
    ./fd/options.nix
    ./figma/options.nix
    ./fish/options.nix
    ./flux/options.nix
    ./fonts/options.nix
    ./footcards/options.nix
    ./fzf/options.nix
    ./geforce/options.nix
    ./git/options.nix
    ./home/options.nix
    ./homebrew/options.nix
    ./htop/options.nix
    ./hue/options.nix
    ./jetbrains/options.nix
    ./jq/options.nix
    ./just/options.nix
    ./kitty/options.nix
    ./kmonad/options.nix
    ./linear/options.nix
    ./logitech/options.nix
    ./macos/options.nix
    ./nix/options.nix
    ./node/options.nix
    ./obsidian/options.nix
    ./one-password/options.nix
    ./postgresql/options.nix
    ./prettyping/options.nix
    ./python/options.nix
    ./qmk/options.nix
    ./raspberry-pi/options.nix
    ./raycast/options.nix
    ./rclone/options.nix
    ./ripgrep/options.nix
    ./rust/options.nix
    ./skhd/options.nix
    ./spotify/options.nix
    ./ssh/options.nix
    ./steam/options.nix
    ./tailscale/options.nix
    ./tldr/options.nix
    ./tmux/options.nix
    ./vim/options.nix
    ./vscode/options.nix
    ./warp/options.nix
    ./yabai/options.nix
  ];
}
